
import unittest

from nwalign import NeedlemanWunsch


class TestNeedlemanWunsch(unittest.TestCase):

    def test_1(self): # Durbin et al. p. 21
        nw = NeedlemanWunsch("HEAGAWGHEE", "PAWHEAE")
        self.assertEqual(nw.alignment(), ('HEAGAWGHE-E', '--P-AW-HEAE'))
        self.assertEqual(nw.identity(), 0.4)

    def test_2(self):
        seq1 = "VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR"
        seq2 = "VHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH"
        nw = NeedlemanWunsch(seq1, seq2)
        self.assertEqual(nw.alignment(), ('V-LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-DLS-----HGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR', 'VHLTPEEKSAVTALWGKV--NVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH'))
        self.assertAlmostEqual(nw.identity(), 0.4043, 4)
