use Test::Simple tests => 8;
use NWAlign qw(read_matrix needleman_wunsch);

my %m = read_matrix("BLOSUM50");
ok($m{'W'}{'W'} eq 15, "W-W match is 15");
ok($m{'A'}{'X'} eq -1, "A-X match is -1");
my %m2 = read_matrix("BLOSUM62");
ok($m2{'A'}{'A'} eq 4, "A-A match is 4");
ok($m2{'T'}{'*'} eq -4, "T-* match is -4");
# very simple alignment
my %a = needleman_wunsch("HEAGAWGHEE", "PAWHEAE", \%m, 8);
ok($a{'seq1aligned'} eq "HEAGAWGHE-E", "Seq1 is HEAGAWGHE-E");
ok($a{'seq2aligned'} eq "--P-AW-HEAE", "Seq2 is --P-AW-HEAE");
# hemoglobin alignment
my $hemA = "VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR";
my $hemB = "VHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH";
my %a2 = needleman_wunsch($hemA, $hemB, \%m, 8);
my $aln1 = "V-LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-DLS-----HGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR";
my $aln2 = "VHLTPEEKSAVTALWGKV--NVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH";
ok($a2{'seq1aligned'} eq $aln1, "Seq1 is correct");
ok($a2{'seq2aligned'} eq $aln2, "Seq1 is correct");
